### ISSUE TITLE
Error: Unexpected server response: 404

### ISSUE THREAD

**Issue by BohanRen** [Drincann/Mirai-js#124]
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 404
    at ClientRequest.req.on (D:\Coding\BobHBot\node_modules\ws\lib\websocket.js:728:7)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at abortHandshake (D:\Coding\BobHBot\node_modules\ws\lib\websocket.js:896:15)
    at ClientRequest.req.on (D:\Coding\BobHBot\node_modules\ws\lib\websocket.js:728:7)
    [... lines matching original stack trace ...]
    at Socket.Readable.push (_stream_readable.js:224:10)
```

在发过一条消息过后，报错，之后无法发送消息
代码：
```javascript
const { Bot,Message } = require('mirai-js');
const bot = new Bot();

async function Main(){
    // 连接到一个 mirai-api-http 服务
    await bot.open({
        baseUrl: 'http://127.0.0.1:2003',
        verifyKey: '[key]',
        // 要绑定的 qq，须确保该用户已在 mirai-console 登录
        qq: 2400006639,
    });

    console.log("connected!");

    await bot.sendMessage({
        friend: '1550000009',
        // Message 实例，表示一条消息
        message: new Message().addText('hello world!')
    });

    await bot.sendMessage({
        // 群号
        group: '580000000',
        // 是 http server 接口所需的原始格式，若提供则优先使用
        message: [
         { type: 'Plain', text: '1234'},
         { type: 'Image', url:'[URL]'}
     ],
    });

    await bot.close();
}

Main();
```

**Comment by Drincann** [comment]
麻烦提供一下 mirai-api-http 和 mirai-js 的版本号，以及 mirai-api-http 的配置文件。

**Comment by Drincann** [comment]
尝试 POST /sendFriendMessage 来定位问题，不需要带参数，看一下 status code 是 404 还是 400。

**Comment by BohanRen** [comment]
已解决，原因是配置文件中未开启websocket，我以为http和ws只需要二选一即可

**Comment by Drincann** [comment]
是的，需要开启 http 和 ws 这两个 adaptor。

**Comment by BohanRen** [comment]
> 是的，需要开启 http 和 ws 这两个 adaptor。

我还有个问题，在`bot.open`中只设置了http端口，假如ws端口和http端口不一致，miral-js是如何确定ws端口并连接的呢？

**Comment by Drincann** [comment]
> > 是的，需要开启 http 和 ws 这两个 adaptor。
> 
> 我还有个问题，在`bot.open`中只设置了http端口，假如ws端口和http端口不一致，miral-js是如何确定ws端口并连接的呢？

没有相关的处理，这是因为 mirai-api-http v1.x 中并没有 adaptor 的概念，ws 和 http 默认开放在同一个端口。

在 mirai-js 适配 v2.x 时，没有做改动。

如果要分开，为了将来的扩展性，可能要重新抽象一些东西。

**Comment by BohanRen** [comment]
> > > 是的，需要开启 http 和 ws 这两个 adaptor。
> > 
> > 
> > 我还有个问题，在`bot.open`中只设置了http端口，假如ws端口和http端口不一致，miral-js是如何确定ws端口并连接的呢？
> 
> 没有相关的处理，这是因为 mirai-api-http v1.x 中并没有 adaptor 的概念，ws 和 http 默认开放在同一个端口。
> 
> 在 mirai-js 适配 v2.x 时，没有做改动。
> 
> 如果要分开，为了将来的扩展性，可能要重新抽象一些东西。

好的

**Comment by portwatcher** [comment]
我也触发此问题，请问此库如何加载 `setting.yml`？open 方法只能传入 url key qq 等。

**Comment by portwatcher** [comment]
原来是要修改 http sdk 的 setting.yml，没事儿了，stupid me
